#!/bin/sh

if [ -z "$DOCKER_ENCAPS_NAME" ]; then
    if [ -z "$BUILD_TAG" ]; then
        echo "No DOCKER_ENCAPS_NAME or BUILD_TAG"
        exit 1
    fi

    DOCKER_ENCAPS_NAME=$(echo $BUILD_TAG | tr ',' '_')
fi


docker kill $BUILD_TAG
docker rm $BUILD_TAG

