#!/bin/sh

DOCKER_ENCAPS_IMG=${DOCKER_ENCAPS_IMG:-"ubuntu:latest"}
DOCKER_ENCAPS_SHELL=${DOCKER_ENCAPS_SHELL:-"/bin/sh"}

if [ -z "$DOCKER_ENCAPS_NAME" ]; then
    if [ -z "$BUILD_TAG" ]; then
        echo "No DOCKER_ENCAPS_NAME or BUILD_TAG"
        exit 1
    fi

    DOCKER_ENCAPS_NAME=$(echo $BUILD_TAG | tr ',' '_')
fi

UID=`id -u`

if ! docker inspect $DOCKER_ENCAPS_NAME > /dev/null; then
    docker pull $DOCKER_ENCAPS_IMG
    docker run \
        --detach \
        --name $DOCKER_ENCAPS_NAME \
        --user $UID \
        --volume $PWD:$PWD \
        --workdir $PWD \
        $DOCKER_ENCAPS_ARGS \
        $DOCKER_ENCAPS_IMG \
            tail -f /dev/null > /dev/null

    if [ $? -ne 0 ]; then
        echo "Unable to launch container from $DOCKER_ENCAPS_IMG"
        exit 1
    fi
fi

docker exec -i $DOCKER_ENCAPS_NAME $DOCKER_ENCAPS_SHELL < $1
RET=$?

echo "Exit $RET"
exit $RET

