#!/bin/sh

DOCKER_ENCAPS_IMG=${DOCKER_ENCAPS_IMG:-"ubuntu:latest"}
DOCKER_ENCAPS_SHELL=${DOCKER_ENCAPS_SHELL:-"/bin/sh"}

if [ -z "$DOCKER_ENCAPS_NAME" ]; then
    if [ -z "$BUILD_TAG" ]; then
        echo "No DOCKER_ENCAPS_NAME or BUILD_TAG"
        exit 1
    fi

    DOCKER_ENCAPS_NAME=$(echo $BUILD_TAG | sed 's/[^a-zA-Z0-9_.-]/_/g')
fi

if [ -z "$UID" ]; then
    UID=$(id -u)
fi

if ! docker inspect $DOCKER_ENCAPS_NAME > /dev/null; then
    docker pull $DOCKER_ENCAPS_IMG
    docker run \
        --detach \
        --name $DOCKER_ENCAPS_NAME \
        --user $UID \
        --volume $PWD:$PWD \
        --workdir $PWD \
        $DOCKER_ENCAPS_ARGS \
        $DOCKER_ENCAPS_IMG \
            tail -f /dev/null > /dev/null

    if [ $? -ne 0 ]; then
        echo "Unable to launch container from $DOCKER_ENCAPS_IMG"
        exit 1
    fi
fi

TMP_FILE="/tmp/script-$(sha1sum $1 | awk '{print $1}')"

# Copy file in container
docker exec -i $DOCKER_ENCAPS_NAME $DOCKER_ENCAPS_SHELL -c "cat > $TMP_FILE" < $1

# Exec file
docker exec -i --user $UID $DOCKER_ENCAPS_NAME $DOCKER_ENCAPS_SHELL $TMP_FILE
RET=$?

echo "Exit $RET"
exit $RET

